from locators.for_Become_partner import BecomePartnerLocators
from locators.for_contacts_page import ContactsLocators
from locators.for_local_testing import LocalLocators
from locators.for_subscription_types import SubscriptionTypesLocators
from locators.for_footer_testing import FooterLocators