class MainPageLocators():
    LEVEL = '//label[@for="item1"]'
    TYPE_SUBSCRIPTION = '//form/div[2]/div[3]/button'
    CITY_SELECT = '//button[contains(text(), "Город/Район")]'
    ACTIV_SELECT = '//button[contains(text(), "Активности")]'
    POSSIBILITIES_SELECT = '//button[@class="empty" and contains(., "Доп. возможности")]'
    EMAIL = '//main/section[1]/form/div/input'
    EMAIL_2 = '//div[@class="input"]/input[@name="email"]'
    GET = '//section[1]/form/button'
    NAME = '//input[@type="input" and @name="company"]'
    PHONE = '//input[@type="input" and @name="phone"]'
    CITY = '//input[@name="city"]'
    EMPLOYEE = '//section[7]/form/div[4]/input'
    VALUE = '//form/div[3]/button'
    OPTION = '//section[7]/form/div[3]/div/button[1]'
    GET_2 = '//main/section[7]/form/button'
    LOCATOR_ON_MAIN_PAGE = '//h1[@class="top_title"][text()="Сервис Allsports"]'
    LOCATOR_ON_MAIN_PAGE_2 = '//h1[@class="title"]'
    LOCATOR_ON_MAIN_PAGE_3 = '//h3[text()="Делаем спорт частью корпоративной жизни"]'
    LOCATOR_ON_MAIN_PAGE_4 = '//div[@class="title"][text()="Отзывы наших клиентов"]'
    PLATINUM_LEVEL = '//label[text()="Платиновая"]'
    REGION_LEVEL_1 = '//label[text()="Региональная"]'
    GRODNO_CITY = '//label[text()="Гродно"]'
    GOMEL_CITY_1 = '//label[text()="Гомель"]'
    POOL = '//label[text()="Сауна"]'
    POOL_1 = '//label[text()="Бассейн"]'
    RESERVATION_REQUIRED_1 = '//label[text()="Требуется бронирование"]'
    RESERVATION_REQUIRED = '//label[text()="Требуется бронирование"]'
    SUPPLIER = '//button[contains(text(), "Школа плавания (Дворец творчества детей и молодёжи)]'
    SUPPLIER_2 = '//button[contains(text(), "Бассейн “Волна”")]'

    OBJECTS = '//div[@class="table_amount"]/span[1][@class="big_font"]'
    ACTIVITIS = '//div[@class="table_amount"]/span[2][@class="big_font"]'