class HeaderLocators():
    OBJECT_LOCATOR = '//ul/li/a[text()="Объекты"]'
    SUBSCRIPTION_TYPES = '//ul/li/a[text()="Типы подписок"]'
    BECOME_PARTNER = '//ul/li/a[text()="Стать партнером"]'
    CONTACTS = '//ul/li/a[text()="Контакты"]'
    LOCALE_DROPDOWN_SELECTION = '//button[@class="button-select"]'
    FOUND_TEXT_ON_OBJECT_PAGE = 'выберите подписку'
    FOUND_TEXT_ON_SUBSCRIPTION_TYPES_PAGE = 'Типы подписки'
    FOUND_TEXT_ON_BECOME_PARTNER_PAGE = 'Развивайте ваш бизнес с нами!'
    FOUND_TEXT_ON_CONTACTS_PAGE = 'Контакты'
    BY_LOCALE = '//a[@href="/by/"]'
    AM_LOCALE = '//a[@href="/am/"]'
    AM_EN_LOCALE = '//a[@href="/en_am/"]'
    RU_LOCALE = '//a[@href="/ru/"]'
    FOUND_TEXT_ON_BY_LOCALE = 'Минск'
    FOUND_TEXT_ON_AM_LOCALE = 'Գյումրի'
    FOUND_TEXT_ON_AM_EN_LOCALE = 'Վանաձոր'
    FOUND_TEXT_ON_RU_LOCALE = 'Нижний Новгород'
    CITY_LOCATOR = '//div[@class="city-region-select"]//button[@class="empty"]'